// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RICFinance.API.Data;

#nullable disable

namespace RICFinance.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RICFinance.API.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RICFinance.API.Models.BudgetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AAAExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AAAReApp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AAARemainingBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AdditionalSurrender")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BudgetWithheldLapse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsolidatedRemainingBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsolidatedTotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsolidatedTotalExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<decimal>("ExcessReallocation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FirstReleased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<decimal>("FourthReleased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ObjectCodeId")
                        .HasColumnType("int");

                    b.Property<decimal>("PLABudgetAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLAExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLAReApp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLARemainingBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PLATotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SecondReleased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SumOfReleased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SupplementaryBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ThirdReleased")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAAABudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalBudgetAllocation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UHIBudgetAllocated")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UHIExpenditure")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UHIReApp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UHIRemainingBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UHITotalBudget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("FiscalYearId");

                    b.HasIndex("UpdatedById");

                    b.HasIndex("ObjectCodeId", "FiscalYearId")
                        .IsUnique();

                    b.ToTable("BudgetEntries");
                });

            modelBuilder.Entity("RICFinance.API.Models.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .IsUnique();

                    b.ToTable("FiscalYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            IsCurrent = true,
                            StartDate = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = "2024-25"
                        });
                });

            modelBuilder.Entity("RICFinance.API.Models.ObjectCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HeadOfAccount")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ObjectCodes");
                });

            modelBuilder.Entity("RICFinance.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "IT",
                            Email = "admin@ric.gov.pk",
                            FullName = "System Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$rBNrkhL8hPZq3.VhVYPZUOQMTVZjXXL9dGE3fCHN1SXKx6JJqhzGK",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RICFinance.API.Models.AuditLog", b =>
                {
                    b.HasOne("RICFinance.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RICFinance.API.Models.BudgetEntry", b =>
                {
                    b.HasOne("RICFinance.API.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RICFinance.API.Models.FiscalYear", "FiscalYear")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RICFinance.API.Models.ObjectCode", "ObjectCode")
                        .WithMany("BudgetEntries")
                        .HasForeignKey("ObjectCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RICFinance.API.Models.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatedBy");

                    b.Navigation("FiscalYear");

                    b.Navigation("ObjectCode");

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("RICFinance.API.Models.FiscalYear", b =>
                {
                    b.Navigation("BudgetEntries");
                });

            modelBuilder.Entity("RICFinance.API.Models.ObjectCode", b =>
                {
                    b.Navigation("BudgetEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
